version: '3.8'

services:
  app:
    build: .
    container_name: webhook_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo

  dev:
    build: .
    container_name: webhook_app_dev
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    env_file:
      - ./.env
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb: