version: "3.8"
services:
  app:
    build: .
    ports: ["3000:3000"]
    env_file: [.env]
    depends_on: [mongo]
    networks: [webhook_net]

  dev:
    build: .
    ports: ["3001:3000"]
    env_file: [.env]
    volumes:
      - .:/app
      - /app/node_modules
    depends_on: [mongo]
    command: npm run dev
    networks: [webhook_net]

  mongo:
    image: mongo:latest
    ports: ["27017:27017"]
    env_file: [.env]
    volumes: [mongodb:/data/db]
    networks: [webhook_net]

volumes:
  mongodb:

networks:
  webhook_net:
    name: webhook_net
    driver: bridge
